ISMS/urls.py
from django.contrib import admin
from django.urls import path, include
from login import views
from common.views import generate_uuid, get_interface_param, generate_md5
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('login.urls'), name='login'),
    path('organize/', include('organize.urls'), name='organize'),
    path('project/', include('project.urls'), name='project'),
    path('genuuid/', generate_uuid, name='genuuid'),
    path('genmd5/', generate_md5, name='genmd5'),
    path('get_interface_param/<str:interID>/', get_interface_param),
    path('basedata/', include('basedata.urls'), name='basedata'),
    path('user/', include('user.urls'), name='user'),
    path('area/', include('area.urls'), name='area'),
    path('projectmap/', include('projectmap.urls'), name='projectmap'),
    path('team/', include('team.urls'), name='team'),
    path('group/', include('group.urls'), name='group'),
    path('personnel/', include('personnel.urls'), name='personnel'),
    path('personauth/', include('personauth.urls'), name='personauth'),
    path('device/', include('device.urls'), name='device'),
    path('devinterface/', include('devinterface.urls'), name='devinterface'),
    path('pedpassage/', include('pedpassage.urls'), name='pedpassage'),
    path('passagerecord/', include('passagerecord.urls'), name='passagerecord'),
    path('hatrule/', include('hatrule.urls'), name='hatrule'),
    path('hatalertlog/', include('hatalertlog.urls'), name='hatalertlog'),
    path('safetrain/', include('safetrain.urls'), name='safetrain'),
    path('envdatalog/', include('envdatalog.urls'), name='envdatalog'),
    path('envrule/', include('envrule.urls'), name='envrule'),
    path('envalarmlog/', include('envalarmlog.urls'), name='envalarmlog'),
    path('vehiclegate/', include('vehiclegate.urls'), name='vehiclegate'),
    path('vehiclefiles/', include('vehiclefiles.urls'), name='vehiclefiles'),
    path('vehiclepasslog/', include('vehiclepasslog.urls'), name='vehiclepasslog'),
    path('elecfencle/', include('elecfencle.urls'), name='elecfencle'),
    path('elecalarm/', include('elecalarm.urls'), name='elecalarm'),
    path('goodstype/', include('goodstype.urls'), name='goodstype'),
    path('unit/', include('unit.urls'), name='unit'),
    path('materials/', include('materials.urls'), name='materials'),
    path('receaccount/', include('receaccount.urls'), name='receaccount'),
    path('recepound/', include('recepound.urls'), name='recepound'),
    path('issueaccount/', include('issueaccount.urls'), name='issueaccount'),
    path('issuepound/', include('issuepound.urls'), name='issuepound'),
    path('abnpound/', include('abnpound.urls'), name='abnpound'),
    path('menchanical/', include('menchanical.urls'), name='menchanical'),
    path('menccheck/', include('menccheck.urls'), name='menccheck'),
    path('mencrepairplan/', include('mencrepairplan.urls'), name='mencrepairplan'),
    path('mencrepairlog/', include('mencrepairlog.urls'), name='mencrepairlog'),
    path('monitordev/', include('monitordev.urls'), name='monitordev'),
    path('dsps/', include('dsps.urls'), name='dsps'),
    path('envdetection/', include('envdetection.urls'), name='envdetection'),
    path('personinfomap/', include('personinfomap.urls'), name='personinfomap'),
    path('mainanalyse/', include('mainanalyse.urls'), name='mainanalyse'),
    path('elevator/', include('elevator.urls'), name='elevator'),
    path('towercrane/', include('towercrane.urls'), name='towercrane'),
    path('mapview/', include('mapview.urls'), name='mapview'),
    path('visitor/', include('visitor.urls'), name='visitor'),
    path('usergroup/', include('usergroup.urls'), name='usergroup'),
    path('interface/', include('interface.urls'), name='interface'),
    path('unloading/', include('unloading.urls'), name='unloading'),
    path('busmenu/', include('busmenu.urls'), name='busmenu'),
    path('appkey/', include('appkey.urls'), name='appkey'),
    path('ismsapi/', include('ismsapi.urls'), name='ismsapi'),
    path('devinterfacesrv/', include('devinterfacesrv.urls'), name='devinterfacesrv'),
    path('datacockpit/', include('datacockpit.urls'), name='datacockpit'),
    path('devicecockpit/', include('devicecockpit.urls'), name='devicecockpit'),
    path('videocockpit/', include('videocockpit.urls'), name='videocockpit'),
    path('prjprocess/', include('prjprocess.urls'), name='prjprocess'),
    path('epidcockpit/', include('epidcockpit.urls'), name='epidcockpit'),
    path('prjreport/', include('prjreport.urls'), name='prjreport')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

envrule/urls.py
from django.urls import path
from . import views

app_name="envrule"

urlpatterns = [
    path('entrance/', views.entrance.as_view(), name='entrance'),
    path('get_datasource/', views.get_datasource.as_view(), name='get_datasource'),
    path('add/', views.add.as_view(), name='add'),
    path('edit/', views.edit.as_view(), name='edit'),
    path('insert/', views.insert.as_view(), name='insert'),
    path('disabled/', views.disabled.as_view(), name='disabled'),
    path('add_switch/', views.add_switch.as_view(), name='add_switch'),
    path('insert_switch/', views.insert_switch.as_view(), name='insert_switch'),
    path('get_switch_datasource/', views.get_switch_datasource.as_view(), name='get_switch_datasource'),
    path('delete_switch/', views.delete_switch.as_view(), name='delete_switch')

]

goodstype/urls.py
from django.urls import path
from . import views

app_name="goodstype"

urlpatterns = [
    path('entrance/', views.entrance.as_view(), name='entrance'),
    path('get_datasource/', views.get_datasource.as_view(), name='get_datasource'),
    path('add/', views.add.as_view(), name='add'),
    path('edit/', views.edit.as_view(), name='edit'),
    path('insert/', views.insert.as_view(), name='insert'),
    path('delete/', views.delete.as_view(), name='delete'),

    path('add_subtype/', views.add_subtype.as_view(), name='add_subtype'),
    path('get_subtype_datasource/', views.get_subtype_datasource.as_view(), name='get_subtype_datasource'),
    path('insert_subtype/', views.insert_subtype.as_view(), name='insert_subtype'),
    path('delete_subtype/', views.delete_subtype.as_view(), name='delete_subtype'),
]

goodstype/models.py
from django.db import models
import uuid
from six import python_2_unicode_compatible

# Create your models here.

@python_2_unicode_compatible

class goodstype(models.Model):

    TYPE_CHOICES = (
        (None, '请选择数据'),
        (0, '比例偏差'),
        (1, '范围偏差')
    )


    FID = models.UUIDField(primary_key=True, default=uuid.uuid1)
    FPID = models.CharField(max_length=32, blank=True, null=True)
    FGoodsTypeID = models.CharField(max_length=32, verbose_name='物料类型编号', blank=True, null=True)
    FGoodsType = models.CharField(max_length=32, verbose_name='物料类型', blank=True, null=True)
    FDeviationType = models.IntegerField(choices=TYPE_CHOICES, verbose_name='偏差类别', blank=True, null=True)
    FPositiveDeviation = models.FloatField(verbose_name='正偏差', blank=True, null=True)
    FNegativeDeviation = models.FloatField(verbose_name='负偏差', blank=True, null=True)
    FDesc = models.CharField(max_length=1024, verbose_name='描述', blank=True, null=True)
    FStatus = models.BooleanField(default=True, verbose_name='状态')
    CREATED_PRJ = models.CharField(max_length=32, verbose_name='所属项目', blank=True, null=True)
    CREATED_ORG = models.CharField(max_length=32, verbose_name='创建组织', blank=True, null=True)
    CREATED_BY = models.CharField(max_length=32, verbose_name='创建人', blank=True, null=True)
    CREATED_TIME = models.DateTimeField(blank=True, null=True, verbose_name='创建时间')
    UPDATED_BY = models.CharField(max_length=32, verbose_name='更新人', blank=True, null=True)
    UPDATED_TIME = models.DateTimeField(auto_now=True, verbose_name='更新时间')

    class Meta:
        db_table = 'T_GoodsType'
        ordering = ['FPID']

goodstype/forms.py
from django.forms import ModelForm
from django import forms
from django.forms import widgets as Fwidgets
from .models import *

class GoosTypeModelForm(ModelForm):

    class Meta:
        model = goodstype
        fields = '__all__'

        widgets = {
            'FID': Fwidgets.Input(attrs={'type': 'hidden'}),
            'FGoodsTypeID': Fwidgets.Input(attrs={'class': 'layui-input', 'lay-verify': 'required', 'autocomplete': 'off'}),
            'FGoodsType': Fwidgets.Input(attrs={'class': 'layui-input', 'lay-verify': 'required', 'autocomplete': 'off'}),
            'FDeviationType': Fwidgets.Select(attrs={'lay-verify': 'required'}),
            'FPositiveDeviation': Fwidgets.Input(attrs={'class': 'layui-input', 'lay-verify': 'required', 'autocomplete': 'off'}),
            'FNegativeDeviation': Fwidgets.Input(attrs={'class': 'layui-input', 'lay-verify': 'required', 'autocomplete': 'off'}),
            'FDesc': Fwidgets.Input(attrs={'class': 'layui-input', 'autocomplete': 'off'})
        }

class SubTypeModelForm(ModelForm):

    FPID = forms.ChoiceField(widget=forms.Select(attrs={'lay-verify': 'required', 'disabled': 'disabled'}), required=False)

    class Meta:
        model = goodstype
        fields = '__all__'

        widgets = {
            'FID': Fwidgets.Input(attrs={'type': 'hidden'}),
            'FGoodsTypeID': Fwidgets.Input(attrs={'class': 'layui-input', 'lay-verify': 'required', 'autocomplete': 'off'}),
            'FGoodsType': Fwidgets.Input(attrs={'class': 'layui-input', 'lay-verify': 'required', 'autocomplete': 'off'}),
            'FDeviationType': Fwidgets.Select(attrs={'lay-verify': 'required'}),
            'FPositiveDeviation': Fwidgets.Input(attrs={'class': 'layui-input', 'lay-verify': 'required', 'autocomplete': 'off'}),
            'FNegativeDeviation': Fwidgets.Input(attrs={'class': 'layui-input', 'lay-verify': 'required', 'autocomplete': 'off'}),
            'FDesc': Fwidgets.Input(attrs={'class': 'layui-input', 'autocomplete': 'off'})
        }

goodstype/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse
from django.http import HttpRequest
from django.shortcuts import redirect
from django.db.models import Q
from .models import goodstype as T_GoodsType
from common.views import *
from django.http import JsonResponse
from .forms import *
import json
from django.utils import timezone
from django.forms import widgets as Fwidge
from django.core.exceptions import ObjectDoesNotExist
from baseframe.baseframe import *
# Create your views here.


#控制器入口
class entrance(EntranceView_base):
    def set_view(self, request):
        self.template_name = 'content/goodstype/goodstypeinfo.html'


#返回table数据及查询结果
class get_datasource(get_datasource_base):
    def get_queryset(self, reqeust):
        prj_id = self.request.session['PrjID']
        serinput = self.request.GET.get("resultdict[FGoodsType]", '')
        goodstype_info =  T_GoodsType.objects.filter(Q(CREATED_PRJ=prj_id), Q(FGoodsType__contains=serinput), Q(FPID__isnull=True))

        return goodstype_info


#链接增加模板
class add(add_base):
    def set_view(self, request):

        self.template_name = 'content/goodstype/goodstypeadd.html'
        self.objForm = GoosTypeModelForm

#链接编辑模板
class edit(edit_base):
    def set_view(self, request):

        self.template_name = 'content/goodstype/goodstypeadd.html'
        self.model = T_GoodsType
        self.objForm = GoosTypeModelForm

#处理新增及保存数据
class insert(insert_base):
    def set_view(self, request):
        self.model = T_GoodsType
        self.objForm = GoosTypeModelForm

#处理删除大类
class delete(delete_base):
    def set_view(self,request):
        fid = ''.join(str(self.request.POST.get('fid')).split('-'))
        self.model = T_GoodsType

        if T_GoodsType.objects.filter(Q(FPID=fid)).count() > 0:
            self.response_data['result'] = '2'
            self.response_data['message'] = '该大类下有子类明细，不允许删除'



#链接新增物料子类模板
class add_subtype(add_base):
    def set_view(self, request):
        fid = ''.join(str(self.request.GET.get('fid')).split('-'))

        self.template_name = 'content/goodstype/goodssubtypeadd.html'
        self.objForm = SubTypeModelForm
        self.query_sets = [
            T_GoodsType.objects.filter(Q(FPID__isnull=True))
        ]
        self.query_set_idfields = ['FPID']
        self.query_set_valuefields = ['FGoodsType']

        self.context['fid'] = fid

#返回物料子类数据table
class get_subtype_datasource(get_datasource_base):
    def get_queryset(self, reqeust):

        fid = self.request.GET.get('fid')

        subtype_info = T_GoodsType.objects.filter(Q(FPID=fid))
        return subtype_info


#处理物料子类新增及保存
class insert_subtype(insert_base):
    def set_view(self, request):
        self.model = T_GoodsType
        self.objForm = SubTypeModelForm
        self.query_sets = [
            T_GoodsType.objects.filter(Q(FPID__isnull=True))
        ]
        self.query_set_idfields = ['FPID']
        self.query_set_valuefields = ['FGoodsType']

        self.type = 1


#处理物料子类删除
class delete_subtype(delete_base):
    def set_view(self,request):
        self.model = T_GoodsType
        self.response_data['result'] = '0'

templates/content/goodstype/goodstypeadd.html
<!DOCTYPE html>
<html>
<head>
  {% include "common/resfiles.html" %}
</head>
<body>

<form class="layui-form layui-form-pane" accept-charset="utf-8">
    <div style="padding: 10px; background-color: #F2F2F2;">
        <div>
            <button class="layui-btn layui-btn-normal" lay-submit lay-filter="formsubmit" >保存</button>
            <a href="javascript:;" class="layui-btn layui-btn-danger" id="btnC">关闭</a>
        </div>

        <div class="layui-row layui-col-space10" style="padding-top: 1%">
            <div class="layui-col-md12">
                <div class="layui-card">
                    <div class="layui-card-header">物料大类</div>
                    <div class="layui-card-body">
                        <div class="layui-row layui-col-space15">
                            <div class="layui-col-xs4">
                                <label class="layui-form-label" style="color: red">大类编码</label>
                                <div class="layui-input-block">
                                    {{ obj.FID }}
                                    {{ obj.FGoodsTypeID }}
                                </div>
                            </div>

                            <div class="layui-col-xs4">
                                <label class="layui-form-label" style="color: red">大类名称</label>
                                <div class="layui-input-block">
                                    {{ obj.FGoodsType }}
                                </div>
                            </div>

                            <div class="layui-col-xs4">
                                <label class="layui-form-label" style="color: red">偏差类别</label>
                                <div class="layui-input-block">
                                    {{ obj.FDeviationType }}
                                </div>
                            </div>
                        </div>

                        <div class="layui-row layui-col-space15">
                            <div class="layui-col-xs4">
                                <label class="layui-form-label" style="color: red">正偏差</label>
                                <div class="layui-input-block">
                                    {{ obj.FPositiveDeviation }}
                                </div>
                            </div>

                            <div class="layui-col-xs4">
                                <label class="layui-form-label" style="color: red">负偏差</label>
                                <div class="layui-input-block">
                                    {{ obj.FNegativeDeviation }}
                                </div>
                            </div>
                        </div>

                        <div class="layui-row layui-col-space10">
                            <div class="layui-col-xs12">
                                <label class="layui-form-label">备注</label>
                                <div class="layui-input-block">
                                    {{ obj.FDesc }}
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>

        {% if action == 'update' %}
            <div class="layui-row layui-col-space10" style="padding-top: 1%">
                <div class="layui-col-md12">
                    <div class="layui-card">
                        <div class="layui-card-header" id="divTrain">物料子类</div>
                        <!-- 表单内容 -->
                        <div class="layui-card-body">
                            <table class="layui-table" id="datasource" lay-filter="toolbar"></table>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>

</form>

<style>
    .layui-unselect dl { max-height:200px; }
</style>

<!-- <script src="//res.layui.com/layui/build/layui.js" charset="utf-8"></script> -->
<!-- 注意：如果你直接复制所有代码到本地，上述js路径需要改成你本地的 -->
{% include "common/jsfiles.html" %}

<script>
var fid = $("#id_FID").val();

layui.use(['element','layer','form', 'table', 'util'], function () {
    var element = layui.element
        , layer = layui.layer
        , form = layui.form
        , table = layui.table
        , util = layui.util;

    //关闭按钮
    $("#btnC").click(function () {
        var index = parent.layer.getFrameIndex(window.name); //得到弹层页面的index
        parent.layer.close(index);
    });

    util.fixbar({
        bgcolor: '#01AAED'
    });

    //监听窗口提交
    form.on('submit(formsubmit)', function (data) {
        $.ajax({
            type: "POST",
            url:  "{% url 'goodstype:insert' %}?actype={{ action }}",
            data: data.field,
            dataType: "json",
            success: function (data) {
                if (data.result=='0') {
                    window.parent.document.getElementById('Goodstype').contentWindow.location.reload();

                    var index = parent.layer.getFrameIndex(window.name); //得到弹层页面的index
                    parent.layer.close(index);
                } else if (data.result=='1'){
                    for (item in data["msg"]){
                        if (data["msg"][item]){
                            layer.tips(data["msg"][item], $("input[name='"+item+"']"));
                        }
                    }
                } else if (data.result=='2') {
                    layer.alert('无效的执行方法');
                }
            }
        });
        return false;
    });

    //控制策略列表table
    table.render({
        elem: '#datasource',
        url: "{% url 'goodstype:get_subtype_datasource' %}?fid="+fid,
        cols: [[
            {field:'FGoodsTypeID', width: '15%', title: '子类编号', sort: true},
            {field:'FGoodsType', width: '20%', title: '子类名称', sort: true},
            {field:'FDeviationType', width: '15%', title: '偏差类别', sort: true, templet: '#tpType'},
            {field:'FPositiveDeviation', width: '15%', title: '正偏差', sort: true},
            {field:'FNegativeDeviation', width: '15%', title: '负偏差', sort: true},
            {field:'FDesc', width: '20%', title: '备注', sort: true},
            {field:'', title: '操作', width: '15%', toolbar: '#tlbar', fixed: 'right'}
        ]],
    });


    //监听工具栏按钮事件
    table.on('tool(toolbar)', function (obj) {
        var data = obj.data;           //获取当前行数据
        var layEvent = obj.event;      //获取当前行事件
        var tr = obj.tr;               //获取当前行tr的DOM数据
        var fid_delete = {"fid":data.FID};

        switch (layEvent){
            case 'delete' :              //编辑按钮事件
                parent.layer.open({
                    content: '是否确定删除该数据',
                    btn: ['确定','取消'],
                    yes: function (index) {
                        $.post("{% url 'envrule:delete_switch' %}", fid_delete, function (data) {
                            if (data.result == '0'){
                                location.reload();
                            } else if (data.result == '1')  {
                                parent.layer.alert('删除失败',{skin: 'layui-layer-lan', closeBtn: 0, anim: 0});
                            }
                        },"json");

                        parent.layer.close(index);
                    },
                    btn2: function (index) {

                    }
                });

                break;

            case '':
                break;
        }
    });



})
</script>

<!--显示偏差类别模板-->
<script type="text/html" id="tpType">
    {% verbatim %}
    {{#  if(d.FDeviationType == 0){ }}
    <span>比例偏差</span>
    {{#  } else if(d.FDeviationType == 1) { }}
    <span>范围偏差</span>
    {{#  } }}
    {% endverbatim %}
</script>

<!--生成操作工具栏-->
<script type="text/html" id="tlbar">
    {% verbatim %}
        <div class="layui-btn-group">
            <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit"><i class="iconfont icon-bianji"></i>编辑</a>
            <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="delete"><i class="fa fa-trash" aria-hidden="true"></i>删除</a>

        </div>
    {% endverbatim %}
</script>

</body>
</html>

templates/content/goodstype/goodstypeinfo.html
<!DOCTYPE html>
<html>
<head>
    {% include "common/resfiles.html" %}
</head>
<body style="overflow: hidden;">

  <!--安全帽规则信息列表  -->

    <!-- 工具条 -->
      <!-- 查询框 -->
      <div class="layui-collapse">
          <div class="layui-colla-item">
              <h2 class="layui-colla-title">查询条件</h2>
              <div class="layui-colla-content">
                  <form class="layui-form" method="post">
                      <div class="layui-inline">
                          <input type="text" name="serinput" placeholder="输入物料类别" autocomplete="off" class="layui-input" value="" style="width: 120%">
                      </div>

                      <div class="layui-inline" style="margin-left: 35px">
                          <input type="button" class="layui-btn layui-btn-small layui-btn-normal layui-icon" lay-submit lay-filter="formsubmit" value="&#xe615;查  询"/>
                      </div>
                  </form>
              </div>
          </div>
      </div>

      <div style="padding-top: 10px" >
        <a href="javascript:;" class="layui-btn layui-btn-normal" id="btnAdd">增加</a>
        <a href="javascript:;" class="layui-btn layui-btn-danger" id="btnClose">关闭</a>
      </div>

      <!-- 数据列表 -->

      <table class="layui-table" id="datasource" lay-filter="toolbar"></table>

{% include "common/jsfiles.html" %}

<script>

  layui.use(['element', 'layer', 'table'], function(){
      var $ = layui.jquery
          ,element = layui.element
          ,table = layui.table
          ,layer = layui.layer;

      $("#btnClose").click(function () {
          window.parent.layui.element.tabDelete('tabMain','Goodstype');
      });


      //新增按钮事件
      $("#btnAdd").click(function () {
          parent.layer.open({
              type:   2,
              title:  '新增物料大类',
              area: ['920px','335px'],
              fixed: false,
              content: "{% url 'goodstype:add' %}",
              resize: false,
              move: false
          });
      });

      table.render({
          page: true,
          limit: 20,
          elem: '#datasource',
          url: "{% url 'goodstype:get_datasource' %}",
          cols: [[
              {field:'FGoodsTypeID', width: '15%', title: '物料大类编号', sort: true},
              {field:'FGoodsType', width: '20%', title: '大类名称', sort: true},
              {field:'FDeviationType', width: '10%', title: '偏差类别', sort: true, templet: '#tpType'},
              {field:'FPositiveDeviation', width: '10%', title: '正偏差', sort: true},
              {field:'FNegativeDeviation', width: '10%', title: '负偏差', sort: true},
              {field:'FDesc', width: '20%', title: '备注', sort: true},
              {field:'', title: '操作', width: '23%', toolbar: '#tlbar', fixed: 'right'}
          ]],
          id: 'runreload'
      });

      //监听查询条件提交
        form.on('submit(formsubmit)', function (data) {
            var serinput = $("input[name='serinput']").val();
            //alert(serinput);
            table.reload('runreload', {where: {resultdict:{FGoodsType: serinput}}});

            return false;
        });


      //监听工具栏按钮事件
      table.on('tool(toolbar)', function (obj) {
          var data = obj.data;           //获取当前行数据
          var layEvent = obj.event;      //获取当前行事件
          var tr = obj.tr;               //获取当前行tr的DOM数据
          var fid_delete = {"fid":data.FID};

          switch (layEvent){
              case 'edit' :              //编辑按钮事件
                  parent.layer.open({
                      type:   2,
                      title:  '编辑物料大类',
                      area: ['920px','550px'],
                      fixed: false,
                      content: "{% url 'goodstype:edit' %}?fid="+data.FID,
                      resize: false,
                      move: false
                  });

                  break;

              case 'addSubType'  :           //添加控制策略按钮
                  parent.layer.open({
                      type:   2,
                      title:  '添加物料子类',
                      area: ['920px','335px'],
                      fixed: false,
                      content: "{% url 'goodstype:add_subtype' %}?fid="+data.FID,
                      resize: false,
                      move: false
                  });

                  break;

              case 'delete' :              //编辑按钮事件
                  parent.layer.open({
                      content: '是否确定删除该数据',
                      btn: ['确定','取消'],
                      yes: function (index) {
                          $.post("{% url 'goodstype:delete' %}", fid_delete, function (data) {
                              if (data.result == '0'){
                                  location.reload();
                              } else if (data.result == '1')  {
                                  parent.layer.alert('删除失败',{skin: 'layui-layer-lan', closeBtn: 0, anim: 0});
                              } else if (data.result == '2') {
                                  parent.layer.alert(data.message ,{skin: 'layui-layer-lan', closeBtn: 0, anim: 0});

                              }
                          },"json");

                          parent.layer.close(index);
                      },
                      btn2: function (index) {

                      }
                  });

                  break;
          }
      });
  });
</script>


<!--显示偏差类别模板-->
<script type="text/html" id="tpType">
     {% verbatim %}
        {{#  if(d.FDeviationType == 0){ }}
            <span>比例偏差</span>
        {{#  } else if(d.FDeviationType == 1) { }}
            <span>范围偏差</span>
        {{#  } }}
     {% endverbatim %}
</script>

<!--生成操作工具栏-->
<script type="text/html" id="tlbar">
    {% verbatim %}
        <div class="layui-btn-group">
            <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit"><i class="iconfont icon-bianji"></i>编辑</a>
            <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="addSubType"><i class="fa fa-outdent" aria-hidden="true"></i>添加子类</a>
            <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="delete"><i class="iconfont icon-shanchu"></i>删除</a>
        </div>
    {% endverbatim %}
</script>

</body>
</html>