ISMS/urls.py
from django.contrib import admin
from django.urls import path, include
from login import views
from common.views import generate_uuid, get_interface_param, generate_md5
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('login.urls'), name='login'),
    path('organize/', include('organize.urls'), name='organize'),
    path('project/', include('project.urls'), name='project'),
    path('genuuid/', generate_uuid, name='genuuid'),
    path('genmd5/', generate_md5, name='genmd5'),
    path('get_interface_param/<str:interID>/', get_interface_param),
    path('basedata/', include('basedata.urls'), name='basedata'),
    path('user/', include('user.urls'), name='user'),
    path('area/', include('area.urls'), name='area'),
    path('projectmap/', include('projectmap.urls'), name='projectmap'),
    path('team/', include('team.urls'), name='team'),
    path('group/', include('group.urls'), name='group'),
    path('personnel/', include('personnel.urls'), name='personnel'),
    path('personauth/', include('personauth.urls'), name='personauth'),
    path('device/', include('device.urls'), name='device'),
    path('devinterface/', include('devinterface.urls'), name='devinterface'),
    path('pedpassage/', include('pedpassage.urls'), name='pedpassage'),
    path('passagerecord/', include('passagerecord.urls'), name='passagerecord'),
    path('hatrule/', include('hatrule.urls'), name='hatrule'),
    path('hatalertlog/', include('hatalertlog.urls'), name='hatalertlog'),
    path('safetrain/', include('safetrain.urls'), name='safetrain'),
    path('envdatalog/', include('envdatalog.urls'), name='envdatalog'),
    path('envrule/', include('envrule.urls'), name='envrule'),
    path('envalarmlog/', include('envalarmlog.urls'), name='envalarmlog'),
    path('vehiclegate/', include('vehiclegate.urls'), name='vehiclegate'),
    path('vehiclefiles/', include('vehiclefiles.urls'), name='vehiclefiles'),
    path('vehiclepasslog/', include('vehiclepasslog.urls'), name='vehiclepasslog'),
    path('elecfencle/', include('elecfencle.urls'), name='elecfencle'),
    path('elecalarm/', include('elecalarm.urls'), name='elecalarm'),
    path('goodstype/', include('goodstype.urls'), name='goodstype'),
    path('unit/', include('unit.urls'), name='unit'),
    path('materials/', include('materials.urls'), name='materials'),
    path('receaccount/', include('receaccount.urls'), name='receaccount'),
    path('recepound/', include('recepound.urls'), name='recepound'),
    path('issueaccount/', include('issueaccount.urls'), name='issueaccount'),
    path('issuepound/', include('issuepound.urls'), name='issuepound'),
    path('abnpound/', include('abnpound.urls'), name='abnpound'),
    path('menchanical/', include('menchanical.urls'), name='menchanical'),
    path('menccheck/', include('menccheck.urls'), name='menccheck'),
    path('mencrepairplan/', include('mencrepairplan.urls'), name='mencrepairplan'),
    path('mencrepairlog/', include('mencrepairlog.urls'), name='mencrepairlog'),
    path('monitordev/', include('monitordev.urls'), name='monitordev'),
    path('dsps/', include('dsps.urls'), name='dsps'),
    path('envdetection/', include('envdetection.urls'), name='envdetection'),
    path('personinfomap/', include('personinfomap.urls'), name='personinfomap'),
    path('mainanalyse/', include('mainanalyse.urls'), name='mainanalyse'),
    path('elevator/', include('elevator.urls'), name='elevator'),
    path('towercrane/', include('towercrane.urls'), name='towercrane'),
    path('mapview/', include('mapview.urls'), name='mapview'),
    path('visitor/', include('visitor.urls'), name='visitor'),
    path('usergroup/', include('usergroup.urls'), name='usergroup'),
    path('interface/', include('interface.urls'), name='interface'),
    path('unloading/', include('unloading.urls'), name='unloading'),
    path('busmenu/', include('busmenu.urls'), name='busmenu'),
    path('appkey/', include('appkey.urls'), name='appkey'),
    path('ismsapi/', include('ismsapi.urls'), name='ismsapi'),
    path('devinterfacesrv/', include('devinterfacesrv.urls'), name='devinterfacesrv'),
    path('datacockpit/', include('datacockpit.urls'), name='datacockpit'),
    path('devicecockpit/', include('devicecockpit.urls'), name='devicecockpit'),
    path('videocockpit/', include('videocockpit.urls'), name='videocockpit'),
    path('prjprocess/', include('prjprocess.urls'), name='prjprocess'),
    path('epidcockpit/', include('epidcockpit.urls'), name='epidcockpit'),
    path('prjreport/', include('prjreport.urls'), name='prjreport')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

organize/urls.py
from django.urls import path
from . import views

app_name="organize"

urlpatterns = [
    path('organize/', views.organize, name='organize'),
    path('get_datasource/', views.get_datasource, name='get_datasource'),
    path('add/', views.add, name='add'),
    path('edit/', views.edit, name='edit'),
    path('insert/', views.insert, name='insert'),
    path('disable/', views.disabled, name='disabled'),
    path('show_upload/', views.show_upload, name='show_upload'),
    path('get_quailfications/', views.get_quailfications, name='get_quailfications'),
    path('delete/', views.delete, name='delete'),
]

organize/models.py
from django.db import models
import uuid
from six import python_2_unicode_compatible
import urllib
from django.core.files import File
import os

# Create your models here.

@python_2_unicode_compatible

class organize(models.Model):

    FID = models.UUIDField(primary_key=True, default=uuid.uuid1)
    FOrgID = models.CharField(max_length=32, verbose_name='统一社会信用代码', unique=True, error_messages={'unique': '信用代码重复'})
    FQualevel = models.CharField(max_length=32, verbose_name='主项资质等级', blank=True, null=True)
    FOrgname = models.CharField(max_length=32, verbose_name='组织名称', unique=True, error_messages={'unique': '组织名称重复'})
    FOrgtypeID = models.CharField(max_length=32, verbose_name='组织类型')
    provid = models.CharField(max_length=32, verbose_name='所属省份', blank=True, null=True)
    cityid = models.CharField(max_length=32, verbose_name='所属城市', blank=True, null=True)
    areaid = models.CharField(max_length=32, verbose_name='所属区域', blank=True, null=True)
    FOrgaddress = models.CharField(max_length=128, verbose_name='组织地址', blank=True, null=True)
    FLong = models.FloatField(verbose_name='经度', blank=True, null=True)
    FLat = models.FloatField(verbose_name='经度', blank=True, null=True)
    FLar = models.CharField(max_length=32, verbose_name='法人代表', blank=True, null=True)
    FLartel = models.CharField(max_length=32, verbose_name='法人代表电话', blank=True, null=True)
    FLarIDcard = models.CharField(max_length=50, verbose_name='法人代表身份证', blank=True, null=True)
    FRegcapital = models.DecimalField(max_digits=32, decimal_places=8, verbose_name='注册资金', blank=True, null=True)
    FRegDate = models.DateField(verbose_name='注册日期', blank=True, null=True)
    FLicenceno = models.CharField(max_length=128, verbose_name='安全施工许可证号', blank=True, null=True)
    FValidDate = models.DateField(verbose_name='许可证有效日期', blank=True, null=True)
    FLicauthority = models.CharField(max_length=32, verbose_name='发证机关', blank=True, null=True)
    FHrcharge = models.CharField(max_length=32, verbose_name='劳资负责人姓名', blank=True, null=True)
    FHrIDcard = models.CharField(max_length=128, verbose_name='劳资负责人身份证', blank=True, null=True)
    FHrtel = models.CharField(max_length=32, verbose_name='劳资负责人电话', blank=True, null=True)
    FIssplit = models.BooleanField(default=True, verbose_name='是否数据隔离')
    FStatus = models.BooleanField(default=True, verbose_name='状态')
    FScope = models.CharField(max_length=1000, verbose_name='经营范围', blank=True, null=True)

    #劳务实名制接口所需字段
    FCorpType = models.CharField(max_length=32, verbose_name='企业性质', blank=True, null=True)  #按照建市[2014]108号全国建筑市场监管与诚信信息系统基础数据库标准（试行）规定的编码及类型。
    FLicenseNum = models.CharField(max_length=32, verbose_name='工商营业执照注册号', blank=True, null=True)

    #通用字段
    CREATED_ORG = models.CharField(max_length=32, verbose_name='创建组织', blank=True, null=True)
    CREATED_BY = models.CharField(max_length=32, verbose_name='创建人', blank=True, null=True)
    CREATED_TIME = models.DateTimeField(blank=True, null=True, verbose_name='创建时间')
    UPDATED_BY = models.CharField(max_length=32, verbose_name='更新人', blank=True, null=True)
    UPDATED_TIME = models.DateTimeField(auto_now=True, verbose_name='更新时间')

    class Meta:
        db_table = "T_Organize"


class orgQualifications(models.Model):

    FID = models.UUIDField(primary_key=True, default=uuid.uuid1)
    FPID = models.CharField(max_length=32, blank=True, null=True)
    FQualification = models.CharField(max_length=32, verbose_name='资质名称')
    FFilename = models.CharField(max_length=32, verbose_name='文件名称', blank=True, null=True)
    FFilepath = models.ImageField(upload_to='orgqualpic/', blank=True, null=True)
    CREATED_ORG = models.CharField(max_length=32, verbose_name='创建组织', blank=True, null=True)
    CREATED_BY = models.CharField(max_length=32, verbose_name='创建人', blank=True, null=True)
    CREATED_TIME = models.DateTimeField(blank=True, null=True, verbose_name='创建时间')
    UPDATED_BY = models.CharField(max_length=32, verbose_name='更新人', blank=True, null=True)
    UPDATED_TIME = models.DateTimeField(auto_now=True, verbose_name='更新时间')

    class Meta:
        db_table = "T_OrgQualifications"

organize/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse
from django.shortcuts import redirect
from .models import organize as T_Organize
from .models import orgQualifications as T_OrgQualifications
from basedata.models import base
from django.db.models import Q
from common.views import *
from django.http import JsonResponse
from .forms import *
import json
from django.utils import timezone
from django.forms import widgets as Fwidge
from django.core.exceptions import ObjectDoesNotExist
from django.core.files.base import ContentFile
from django.conf import settings

#组织管理控制器入口
def organize(request):
    #传递组织类型字典到前台页面
    setdata_info = base.objects.filter(Q(FPID='9defe198a17f11e992e7708bcdb9b39a'))
    setdata = get_dict_table(setdata_info, 'FID', 'FBase')

    return render(request, 'content/organize/organizeinfo.html', {'setdata': setdata})

#返回table数据及查询结果
def get_datasource(request):
    serinput = request.POST.get("resultdict[FOrgname]", '')

    Organize_info = T_Organize.objects.filter(Q(FOrgname__contains=serinput))
    Organize_info = org_split(Organize_info, request)

    dict = convert_to_dicts(Organize_info)
    resultdict = {'code':0, 'msg':"", 'count': Organize_info.count(), 'data': dict}

    return  JsonResponse(resultdict, safe=False)

def ref_dropdowndata(obj, request):
    Orgtype_info = base.objects.filter(Q(FPID='9defe198a17f11e992e7708bcdb9b39a'))
    obj.fields['FOrgtypeID'].choices = get_dict_object(request, Orgtype_info, 'FID', 'FBase')

#链接增加模板
def add(request):
    obj = OrganizeModelForm()

    ref_dropdowndata(obj, request)

    return render(request, "content/organize/organizeadd.html" , {'obj': obj, 'action': 'insert'})

#链接编辑模板
def edit(request):
    fid = request.GET.get('fid')

    Organize_info = T_Organize.objects.get(FID=fid)

    obj = OrganizeModelForm(instance=Organize_info)

    ref_dropdowndata(obj, request)

    return render(request, "content/organize/organizeadd.html", {'obj': obj, 'Organize_info': Organize_info, 'action': 'update' })

#处理新增及保存
def insert(request):
    try:
        if request.method == 'POST':
            response_data = {}

            if request.GET.get('actype') == 'insert':
                obj = OrganizeModelForm(request.POST)
            elif request.GET.get('actype') == 'update':
                fid = request.POST.get('FID')
                Organize_info = T_Organize.objects.get(FID=fid)
                obj = OrganizeModelForm(request.POST, instance=Organize_info)
            else:
                response_data['result'] = '2'
                return HttpResponse(json.dumps(response_data))

            ref_dropdowndata(obj, request)

            try:
                if obj.is_valid():
                    temp = obj.save(commit=False)
                    if request.GET.get('actype') == 'insert':
                        temp.FIssplit = True
                        temp.FStatus = True
                    temp.CREATED_ORG = request.session['UserOrg']
                    temp.CREATED_BY = request.session['UserID']
                    temp.UPDATED_BY = request.session['UserID']
                    temp.CREATED_TIME = timezone.now()

                    temp.save()
                    response_data['result'] = '0'
                else:
                    #response_data['msg'] = obj.errors
                    #response_data['result'] = '1'

                    ErrorDict = obj.errors

                    Error_Str = json.dumps(ErrorDict)

                    Error_Dict = json.loads(Error_Str)

                return HttpResponse(json.dumps(response_data))

            except Exception as e:
                response_data['msg'] = e
                response_data['result'] = '1'

                return HttpResponse(json.dumps(response_data))
    except Exception as e:
        print(e)


#处理禁用/启用组织
def disabled(request):
    response_data = {}
    if request.method == 'POST':
        fid = request.POST.get('fid')

        try:
            Orgtype_info = T_Organize.objects.get(FID=fid)

            if request.GET.get('type') == 'lock':
                Orgtype_info.FStatus = False
            elif request.GET.get('type') == 'unlock':
                Orgtype_info.FStatus = True

            Orgtype_info.save()

            response_data['result'] = '0'
            return HttpResponse(json.dumps(response_data))
        except ObjectDoesNotExist:
            response_data['result'] = '2'
            return HttpResponse(json.dumps(response_data))

    else:
        response_data['result'] = '2'
        return HttpResponse(json.dumps(response_data))

#链接上传图片窗口
def show_upload(request):
    obj = OrganizeQualiModeForm()
    fid = ''.join(str(request.GET.get('fid')).split('-'))

    if request.method == 'POST':
        obj = OrganizeQualiModeForm(request.POST, request.FILES)


        if obj.is_valid():
            temp = obj.save(commit=False)
            temp.FPID = request.POST.get('FPID')
            temp.CREATED_ORG = request.session['UserOrg']
            temp.CREATED_BY = request.session['UserID']
            temp.UPDATED_BY = request.session['UserID']
            temp.CREATED_TIME = timezone.now()

            temp.save()
            
            url = '/organize/show_upload?fid='+request.POST.get('FPID')
            return redirect(url)

    else:
        return render(request, "content/organize/orgainizeupload.html", {'obj': obj, 'fid': fid})

#图片明细数据源
def get_quailfications(request):

    if request.method == 'GET':
        fpid = ''.join(str(request.GET.get('fid')).split('-'))

        Qualifications_info = T_OrgQualifications.objects.filter(Q(FPID=fpid))

        dict = convert_to_dicts(Qualifications_info)
        resultdict = {'code':0, 'msg':"", 'count': Qualifications_info.count(), 'data': dict}

        return  JsonResponse(resultdict, safe=False)

#删除资质文件
def delete(request):
    response_data = {}
    if request.method == 'POST':

        fid = request.POST.get('fid')

        try:
            Qualifications_info = T_OrgQualifications.objects.get(Q(FID=fid))

            the_file = settings.BASE_DIR + os.sep +"media" + os.sep + str(Qualifications_info.FFilepath)

            Qualifications_info.delete()

            if os.path.exists(the_file):
                os.remove(the_file)
                response_data['result'] = '0'
            else:
                response_data['result'] = '1'

            return HttpResponse(json.dumps(response_data))

        except Exception as e:

            response_data['result'] = '2'
            return HttpResponse(json.dumps(response_data))

templates/content/organize/orgainizeupload.html
<!DOCTYPE html>
<html>
<head>
  {% include "common/resfiles.html" %}
</head>
<body style="overflow: hidden">


<form class="layui-form layui-form-pane" action="{{ request.path }}" method="post" enctype="multipart/form-data">
    <!-- 工具栏按钮 -->
    <div style="padding-top: 1%; padding-left: 1%">
      <!-- <button class="layui-btn layui-btn-normal" lay-submit lay-filter="formsubmit" >上传</button> -->
      <button type="submit" class="layui-btn layui-btn-normal">上传</button>
      <a href="javascript:;" class="layui-btn layui-btn-danger" id="btnC">关闭</a>
    </div>
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
      <legend>组织资质信息</legend>
    </fieldset>
    <!-- 表单内容 -->
    <div class="layui-row layui-col-space10" style="padding-left: 2%">
      <div class="layui-col-xs12">
          <label class="layui-form-label" style="color: red">资质名称</label>
          <div class="layui-input-block">
              {{ obj.FID }}
              <input type="hidden" name="FPID" id="FPID" value="{{ fid }}">
              {{ obj.FQualification }}
          </div>
      </div>
    </div>

    <div class="layui-row layui-col-space10" style="padding-left: 2%">
        <div class="layui-col-xs12">
            <label class="layui-form-label" style="color: red">资质图片</label>
            <div class="layui-input-block">
                <button type="button" class="layui-btn layui-btn-normal" id="btnUpload">选择资质文件</button>
                {{ obj.FFilepath }}
                <span id="document_name">未上传文件</span>
            </div>
        </div>
    </div>

</form>

<!-- <script src="//res.layui.com/layui/build/layui.js" charset="utf-8"></script> -->
<!-- 注意：如果你直接复制所有代码到本地，上述js路径需要改成你本地的 -->
{% include "common/jsfiles.html" %}

<script>
layui.use(['element','layer','form', 'laydate'], function () {
    var element = layui.element
        , layer = layui.layer
        , form = layui.form
        , laydate = layui.laydate;


    //关闭按钮
    $("#btnC").click(function () {
        var index = parent.layer.getFrameIndex(window.name); //得到弹层页面的index
        parent.layer.close(index);
    });

        $("#btnUpload").click(function () {
            $("#id_FFilepath").click()
        });

        $("#id_FFilepath").change(function(e){
	        var name=e.currentTarget.files[0].name;
	        $("#document_name").html(name);
        });
})
</script>


</body>
</html>

templates/content/organize/organizeinfo.html
<!DOCTYPE html>
<html>
<head>
    {% include "common/resfiles.html" %}
</head>
<body style="overflow: hidden;">

  <!--组织信息列表  -->

    <!-- 工具条 -->
      <form class="layui-form" method="post">
      <div >
        <a href="javascript:;" class="layui-btn layui-btn-normal" id="btnAdd">新增</a>
        <a href="javascript:;" class="layui-btn layui-btn-danger" id="btnClose">关闭</a>
        <!-- 查询框 -->
          <div class="layui-inline" style="margin-left: 30px">
            <input type="text" name="serinput" placeholder="请输入需要查询的类别名称" autocomplete="off" class="layui-input" style="width: 120%">
          </div>
          <div class="layui-inline" style="margin-left: 35px">
            <input type="button" class="layui-btn layui-btn-small layui-btn-normal layui-icon" lay-submit lay-filter="formsubmit" value="&#xe615;查  询"/>
          </div>
      </div>
      </form>
    <!-- 数据列表 -->
      <table class="layui-table" id="datasource" lay-filter="toolbar"></table>
{% include "common/jsfiles.html" %}

<script>
  var Orgtypedata = {{ setdata|safe }};


  layui.use(['element', 'layer', 'table'], function(){
      var $ = layui.jquery
          ,element = layui.element
          ,table = layui.table
          ,layer = layui.layer;

      $("#btnClose").click(function () {
          window.parent.layui.element.tabDelete('tabMain','Organize');
      });

      //新增按钮事件
      $("#btnAdd").click(function () {
          parent.layer.open({
              type:   2,
              title:  '添加组织资料',
              area: ['1100px','720px'],
              fixed: false,
              content: "{% url 'organize:add' %}",
              resize: false,
              move: false
          });
      });

      table.render({
          method: 'post',
          page: true,
          limit: 15,
          elem: '#datasource',
          url: "{% url 'organize:get_datasource' %}",
          cols: [[
              {field:'FOrgname', width: '20%', title: '组织名称', sort: true},
              {field:'FOrgtypeID', width: '12%', title: '组织类型', sort: true, templet: '<div>{% verbatim %}{{sotitle(d.FOrgtypeID, Orgtypedata)}}{% endverbatim %}</div>'},
              {field:'FOrgID', width: '20%', title: '统一社会信用代码', sort: true},
              {field:'FOrgaddress', width: '20%', title: '组织地址', sort: true},
              {field:'FQualevel', width: '20%', title: '主项资质等级', sort: true},
              {field:'FLar', width: '20%', title: '法人代表', sort: true},
              {field:'FRegcapital', width: '20%', title: '注册资金', sort: true},
              {field:'FRegDate', width: '20%', title: '注册日期', sort: true},
              {field:'FLicenceno', width: '25%', title: '安全施工许可证号', sort: true},
              {field:'FValidDate', width: '20%', title: '许可证有效日期', sort: true},
              {field:'FLicauthority', width: '20%', title: '发证机关', sort: true},
              {field:'FHrcharge', width: '20%', title: '劳资负责人', sort: true},

              {field:'FIssplit', width: '10%', title: '数据隔离', sort: true, templet: '#tpIssplit'},
              {field:'FStatus', width: '10%', title: '状态', sort: true, templet: '#tpStatus'},
              {field:'', title: '操作', width: '22%', toolbar: '#tlbar', fixed: 'right'}
          ]],
          id: 'runreload'
      });

    //监听查询条件提交
     form.on('submit(formsubmit)', function (data) {
        var serinput = $("input[name='serinput']").val();

        table.reload('runreload', {page:{curr: 1}, where: {resultdict:{FOrgname: serinput}}});

        return false;
     });


      //监听工具栏按钮事件
      table.on('tool(toolbar)', function (obj) {
          var data = obj.data;           //获取当前行数据
          var layEvent = obj.event;      //获取当前行事件
          var tr = obj.tr;               //获取当前行tr的DOM数据
          var fid = {"fid":data.FID};

          switch (layEvent){
              case 'edit' :              //编辑按钮事件
                  parent.layer.open({
                      type:   2,
                      title:  '编辑组织资料',
                      area: ['1100px','720px'],
                      fixed: false,
                      content: "{% url 'organize:edit' %}?fid="+data.FID,
                      resize: false,
                      move: false
                  });

                  break;
              case 'disabled' :               //禁用按钮事件
                  parent.layer.open({
                      content: '是否确定禁用该组织',
                      btn: ['确定','取消'],
                      yes: function (index) {
                          $.post("{% url 'organize:disabled' %}?type=lock", fid, function (data) {
                              if (data.result=='0') {
                                  window.parent.document.getElementById('Organize').contentWindow.location.reload();
                              } else if (data.result=='2') {
                                  parent.layer.alert('组织禁用失败',{skin: 'layui-layer-lan', closeBtn: 0, anim: 0});
                              }

                          },"json");

                          parent.layer.close(index);
                      },
                      btn2: function (index) {
                      }
                  });

                  break;

              case 'enabled' :
                  parent.layer.open({
                      content: '是否确定启用该组织',
                      btn: ['确定','取消'],
                      yes: function (index) {
                          $.post("{% url 'organize:disabled' %}?type=unlock", fid, function (data) {
                              if (data.result=='0') {
                                  window.parent.document.getElementById('Organize').contentWindow.location.reload();
                              } else if (data.result=='2') {
                                  parent.layer.alert('组织启用失败',{skin: 'layui-layer-lan', closeBtn: 0, anim: 0});
                              }

                          },"json");

                          parent.layer.close(index);
                      },
                      btn2: function (index) {
                      }
                  });


                  break;

              case 'upload' :
                  parent.layer.open({
                      type:   2,
                      title:  '上传资质文件',
                      area: ['800px','280px'],
                      fixed: false,
                      content: "{% url 'organize:show_upload' %}?fid="+data.FID,
                      resize: false,
                      move: false
                  });

                  break;
          }
      });
  });
</script>

<!--显示启用状态模板-->
<script type="text/html" id="tpStatus">
    {% verbatim %}
        {{#  if(d.FStatus == false){ }}
        <span style="color: red">禁用</span>
        {{#  } else if(d.FStatus == true) { }}
        <span style="color: green">启用</span>
        {{#  } }}
    {% endverbatim %}
</script>

<!--显示用户类型模板-->
<script type="text/html" id="tpIssplit">
    {% verbatim %}
        {{#  if(d.FIssplit == false){ }}
        <span>不隔离</span>
        {{#  } else if(d.FIssplit == true) { }}
        <span>隔离</span>
        {{#  } }}
    {% endverbatim %}
</script>

<!--生成操作工具栏-->
<script type="text/html" id="tlbar">
    {% verbatim %}
        <div class="layui-btn-group">
            <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit"><i class="iconfont icon-bianji"></i>编辑</a>
            <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="upload"><i class="fa fa-picture-o" aria-hidden="true"></i>上传资质文件</a>

            {{# if(d.FStatus == true){ }}
                <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="disabled"><i class="iconfont icon-ccgl-yuliuyusuoding-6"></i>禁用</a>
            {{# } else if(d.FStatus == false){ }}
                <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="enabled"><i class="iconfont icon-ccgl-yuliuyusuoding-6"></i>启用</a>
            {{# } else { }}
                <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="disabled"><i class="iconfont icon-ccgl-yuliuyusuoding-6"></i>禁用</a>
            {{# } }}

        </div>
    {% endverbatim %}
</script>


</body>
</html>