ISMS/urls.py
from django.contrib import admin
from django.urls import path, include
from login import views
from common.views import generate_uuid, get_interface_param, generate_md5
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('login.urls'), name='login'),
    path('organize/', include('organize.urls'), name='organize'),
    path('project/', include('project.urls'), name='project'),
    path('genuuid/', generate_uuid, name='genuuid'),
    path('genmd5/', generate_md5, name='genmd5'),
    path('get_interface_param/<str:interID>/', get_interface_param),
    path('basedata/', include('basedata.urls'), name='basedata'),
    path('user/', include('user.urls'), name='user'),
    path('area/', include('area.urls'), name='area'),
    path('projectmap/', include('projectmap.urls'), name='projectmap'),
    path('team/', include('team.urls'), name='team'),
    path('group/', include('group.urls'), name='group'),
    path('personnel/', include('personnel.urls'), name='personnel'),
    path('personauth/', include('personauth.urls'), name='personauth'),
    path('device/', include('device.urls'), name='device'),
    path('devinterface/', include('devinterface.urls'), name='devinterface'),
    path('pedpassage/', include('pedpassage.urls'), name='pedpassage'),
    path('passagerecord/', include('passagerecord.urls'), name='passagerecord'),
    path('hatrule/', include('hatrule.urls'), name='hatrule'),
    path('hatalertlog/', include('hatalertlog.urls'), name='hatalertlog'),
    path('safetrain/', include('safetrain.urls'), name='safetrain'),
    path('envdatalog/', include('envdatalog.urls'), name='envdatalog'),
    path('envrule/', include('envrule.urls'), name='envrule'),
    path('envalarmlog/', include('envalarmlog.urls'), name='envalarmlog'),
    path('vehiclegate/', include('vehiclegate.urls'), name='vehiclegate'),
    path('vehiclefiles/', include('vehiclefiles.urls'), name='vehiclefiles'),
    path('vehiclepasslog/', include('vehiclepasslog.urls'), name='vehiclepasslog'),
    path('elecfencle/', include('elecfencle.urls'), name='elecfencle'),
    path('elecalarm/', include('elecalarm.urls'), name='elecalarm'),
    path('goodstype/', include('goodstype.urls'), name='goodstype'),
    path('unit/', include('unit.urls'), name='unit'),
    path('materials/', include('materials.urls'), name='materials'),
    path('receaccount/', include('receaccount.urls'), name='receaccount'),
    path('recepound/', include('recepound.urls'), name='recepound'),
    path('issueaccount/', include('issueaccount.urls'), name='issueaccount'),
    path('issuepound/', include('issuepound.urls'), name='issuepound'),
    path('abnpound/', include('abnpound.urls'), name='abnpound'),
    path('menchanical/', include('menchanical.urls'), name='menchanical'),
    path('menccheck/', include('menccheck.urls'), name='menccheck'),
    path('mencrepairplan/', include('mencrepairplan.urls'), name='mencrepairplan'),
    path('mencrepairlog/', include('mencrepairlog.urls'), name='mencrepairlog'),
    path('monitordev/', include('monitordev.urls'), name='monitordev'),
    path('dsps/', include('dsps.urls'), name='dsps'),
    path('envdetection/', include('envdetection.urls'), name='envdetection'),
    path('personinfomap/', include('personinfomap.urls'), name='personinfomap'),
    path('mainanalyse/', include('mainanalyse.urls'), name='mainanalyse'),
    path('elevator/', include('elevator.urls'), name='elevator'),
    path('towercrane/', include('towercrane.urls'), name='towercrane'),
    path('mapview/', include('mapview.urls'), name='mapview'),
    path('visitor/', include('visitor.urls'), name='visitor'),
    path('usergroup/', include('usergroup.urls'), name='usergroup'),
    path('interface/', include('interface.urls'), name='interface'),
    path('unloading/', include('unloading.urls'), name='unloading'),
    path('busmenu/', include('busmenu.urls'), name='busmenu'),
    path('appkey/', include('appkey.urls'), name='appkey'),
    path('ismsapi/', include('ismsapi.urls'), name='ismsapi'),
    path('devinterfacesrv/', include('devinterfacesrv.urls'), name='devinterfacesrv'),
    path('datacockpit/', include('datacockpit.urls'), name='datacockpit'),
    path('devicecockpit/', include('devicecockpit.urls'), name='devicecockpit'),
    path('videocockpit/', include('videocockpit.urls'), name='videocockpit'),
    path('prjprocess/', include('prjprocess.urls'), name='prjprocess'),
    path('epidcockpit/', include('epidcockpit.urls'), name='epidcockpit'),
    path('prjreport/', include('prjreport.urls'), name='prjreport')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mencrepairplan/urls.py
from django.urls import path
from . import views

app_name="mencrepairplan"

urlpatterns = [
    path('entrance/', views.entrance.as_view(), name='entrance'),
    path('get_datasource/', views.get_datasource.as_view(), name='get_datasource'),
    path('add/', views.add.as_view(), name='add'),
    path('edit/', views.edit.as_view(), name='edit'),
    path('insert/', views.insert.as_view(), name='insert'),
    path('disabled/', views.disabled.as_view(), name='disabled')
]

mencrepairplan/models.py
from django.db import models
import uuid
from menchanical.models import menchanical
from six import python_2_unicode_compatible

# Create your models here.

@python_2_unicode_compatible

class mencrepairplan(models.Model):

    TYPE_CHOICES = (
        (None, '请选择数据'),
        (0, '固定频率'),
        (1, '随机抽查')
    )


    FID = models.UUIDField(primary_key=True, default=uuid.uuid1)
    FMecserialFID = models.ForeignKey(menchanical, to_field='FID', on_delete=models.CASCADE, blank=True, null=True)
    FChecktype = models.IntegerField(choices=TYPE_CHOICES, verbose_name='检查类型', blank=True, null=True)
    FInterval = models.IntegerField(verbose_name='固定频率时间', blank=True, null=True)
    FFirstcheckdate = models.DateField(verbose_name='首次检查日期', blank=True, null=True)
    FStatus = models.BooleanField(default=True, verbose_name='状态')
    FDesc = models.CharField(max_length=1024, verbose_name='备注', blank=True, null=True)
    CREATED_PRJ = models.CharField(max_length=32, verbose_name='所属项目', blank=True, null=True)
    CREATED_ORG = models.CharField(max_length=32, verbose_name='创建组织', blank=True, null=True)
    CREATED_BY = models.CharField(max_length=32, verbose_name='创建人', blank=True, null=True)
    CREATED_TIME = models.DateTimeField(blank=True, null=True, verbose_name='创建时间')
    UPDATED_BY = models.CharField(max_length=32, verbose_name='更新人', blank=True, null=True)
    UPDATED_TIME = models.DateTimeField(auto_now=True, verbose_name='更新时间')

    class Meta:
        db_table = 'T_MencRepairPlan'

mencrepairplan/forms.py
from django.forms import ModelForm
from django import forms
from django.forms import widgets as Fwidgets
from .models import *

class MencRepairPlanModelForm(ModelForm):
    FMecserialFID_id = forms.ChoiceField(widget=forms.Select(attrs={'lay-verify': 'required'}), required=False)

    class Meta:
        model = mencrepairplan
        fields = '__all__'

        widgets = {
            'FID': Fwidgets.Input(attrs={'type': 'hidden'}),
            'FChecktype': Fwidgets.Select(attrs={'lay-verify': 'required'}),
            'FInterval': Fwidgets.Input(attrs={'class': 'layui-input', 'lay-verify': 'required', 'autocomplete': 'off'}),
            'FFirstcheckdate': Fwidgets.Input(attrs={'class': 'layui-input', 'lay-verify': 'required', 'autocomplete': 'off'}),
            'FStatus': Fwidgets.CheckboxInput(attrs={'lay-skin': 'switch', 'lay-text': '启用|禁用', 'disabled': 'disabled'}),
            'FDesc': Fwidgets.Textarea(attrs={'class': 'layui-textarea', 'autocomplete': 'off', 'rows': '1'})

        }

mencrepairplan/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse
from django.http import HttpRequest
from django.shortcuts import redirect
from django.db.models import Q
from .models import mencrepairplan as T_MencRepairPlan
from basedata.models import base
from menchanical.models import menchanical
from common.views import *
from django.http import JsonResponse
from .forms import *
import json
from django.utils import timezone
from django.forms import widgets as Fwidge
from django.core.exceptions import ObjectDoesNotExist
from baseframe.baseframe import *
# Create your views here.

#控制器入口
class entrance(EntranceView_base):
    def set_view(self, request):
        self.template_name = 'content/mencrepairplan/mencrepairplaninfo.html'
        self.query_sets = [
            base.objects.filter(Q(FPID='a7541a6abd7211e9a59c7831c1d24216')),
        ]
        self.quer_set_fieldnames = ['FBase']


#返回table数据及查询结果
class get_datasource(get_datasource_base):
    def get_queryset(self, reqeust):
        prj_id = self.request.session['PrjID']
        serinput = self.request.GET.get("resultdict[FMecserialFID__FMecserialID]", '')
        self.type = 1
        repairplan_info = T_MencRepairPlan.objects.filter(Q(CREATED_PRJ=prj_id), Q(FMecserialFID__FMecserialID__contains=serinput)).values('FID', 'FMecserialFID__FMecserialID', 'FMecserialFID__FMectypeID','FMecserialFID__FMecspec', 'FChecktype', 'FInterval', 'FFirstcheckdate', 'FStatus', 'FDesc')

        return repairplan_info

#链接增加模板
class add(add_base):
    def set_view(self, request):
        prj_id = self.request.session['PrjID']

        self.template_name = 'content/mencrepairplan/mencrepairplanadd.html'
        self.objForm = MencRepairPlanModelForm

        arr_id = []
        mencserial_info = T_MencRepairPlan.objects.filter(Q(FStatus=True), Q(CREATED_PRJ=prj_id))
        if mencserial_info.count() > 0:
            for obj in mencserial_info:
                str_id = ''.join(str(obj.FMecserialFID_id).split('-'))
                arr_id.append(str_id)


        mench_info = menchanical.objects.filter(Q(FStatus=True), Q(CREATED_PRJ=prj_id), ~Q(FID__in=arr_id))
        self.context['mench'] =  mench_info
        self.context['mencSerial'] = 'null'


#链接编辑模板
class edit(edit_base):
    def set_view(self, request):
        prj_id = self.request.session['PrjID']
        fid = ''.join(str(self.request.GET.get('fid')).split('-'))

        self.template_name = 'content/mencrepairplan/mencrepairplanadd.html'
        self.model = T_MencRepairPlan
        self.objForm = MencRepairPlanModelForm

        mench_info = menchanical.objects.filter(Q(FStatus=True), Q(CREATED_PRJ=prj_id))
        self.context['mench'] =  mench_info

        mencSerial = T_MencRepairPlan.objects.get(Q(FID=fid)).FMecserialFID_id
        self.context['mencSerial'] = mencSerial


#处理新增及保存数据
class insert(insert_base):
    def set_view(self, request):
        prj_id = self.request.session['PrjID']

        self.model = T_MencRepairPlan
        self.objForm = MencRepairPlanModelForm

        self.set_fields = ['FMecserialFID_id']
        self.set_value = [self.request.POST.get('FMecserialFID')]


#处理禁用/启用
class disabled(disabled_base):
    def set_view(self, request):
        self.model = T_MencRepairPlan

templates/content/mencrepairplan/mencrepairplanadd.html
<!DOCTYPE html>
<html>
<head>
  {% include "common/resfiles.html" %}
</head>
<body>

<form class="layui-form layui-form-pane" accept-charset="utf-8">
    <div style="padding: 10px; background-color: #F2F2F2;">
        <div>
            <button class="layui-btn layui-btn-normal" lay-submit lay-filter="formsubmit" >保存</button>
            <a href="javascript:;" class="layui-btn layui-btn-danger" id="btnC">关闭</a>
        </div>

        <div class="layui-row layui-col-space10" style="padding-top: 1%">
            <div class="layui-col-md12">
                <div class="layui-card">
                    <div class="layui-card-header">机械设备运维计划</div>
                    <div class="layui-card-body">
                        <div class="layui-row layui-col-space10">
                            <div class="layui-col-xs4">
                                <label class="layui-form-label" style="color: red">机械编码</label>
                                <div class="layui-input-block">
                                    {{ obj.FID }}

                                    <select name="FMecserialFID" lay-filter="TCommu" id="id_FMecserialFID" lay-verify="required">
                                        <option value="">请选择数据</option>
                                        {% for jj in mench %}
                                            <option value="{{ jj.FID }}" {% if jj.FID == mencSerial %} selected="" {% endif %} >{{ jj.FMecserialID }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>

                            <div class="layui-col-xs4">
                                <label class="layui-form-label">状态</label>
                                <div class="layui-input-block">
                                    {{ obj.FStatus }}
                                </div>
                            </div>
                        </div>

                        <div class="layui-row layui-col-space10">
                            <div class="layui-col-xs4">
                                <label class="layui-form-label" style="color: red">检查类型</label>
                                <div class="layui-input-block">
                                    {{ obj.FChecktype }}
                                </div>
                            </div>

                            <div class="layui-col-xs4">
                                <label class="layui-form-label" style="color: red">检查频次</label>
                                <div class="layui-input-block">
                                    {{ obj.FInterval }}
                                </div>
                            </div>

                            <div class="layui-col-xs4">
                                <label class="layui-form-label" style="color: red">首次检查</label>
                                <div class="layui-input-block">
                                    {{ obj.FFirstcheckdate }}
                                </div>
                            </div>
                        </div>

                        <div class="layui-row layui-col-space10">
                            <div class="layui-col-xs12">
                                <label class="layui-form-label">描述</label>
                                <div class="layui-input-block">
                                    {{ obj.FDesc }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

</form>

<!-- <script src="//res.layui.com/layui/build/layui.js" charset="utf-8"></script> -->
<!-- 注意：如果你直接复制所有代码到本地，上述js路径需要改成你本地的 -->
{% include "common/jsfiles.html" %}


<script>

layui.use(['element','layer','form', 'laydate'], function () {
    var element = layui.element
        , layer = layui.layer
        , form = layui.form
        , laydate = layui.laydate;

    //关闭按钮
    $("#btnC").click(function () {
        var index = parent.layer.getFrameIndex(window.name); //得到弹层页面的index
        parent.layer.close(index);
    });

    laydate.render({
        elem: '#id_FFirstcheckdate',
        trigger: 'click'
    });

    //监听窗口提交
    form.on('submit(formsubmit)', function (data) {
        $.ajax({
            type: "POST",
            url:  "{% url 'mencrepairplan:insert' %}?actype={{ action }}",
            data: data.field,
            dataType: "json",
            success: function (data) {
                if (data.result=='0') {
                    window.parent.document.getElementById('Mencrepairplan').contentWindow.location.reload();

                    var index = parent.layer.getFrameIndex(window.name); //得到弹层页面的index
                    parent.layer.close(index);
                } else if (data.result=='1'){
                    for (item in data["msg"]){
                        if (data["msg"][item]){
                            layer.tips(data["msg"][item], $("input[name='"+item+"']"));
                        }
                    }
                } else if (data.result=='2') {
                    layer.alert('无效的执行方法');
                }
            }
        });
        return false;
    });
})
</script>

</body>
</html>

templates/content/mencrepairplan/mencrepairplaninfo.html
<!DOCTYPE html>
<html>
<head>
    {% include "common/resfiles.html" %}
</head>
<body style="overflow: hidden;">

  <!--安全帽规则信息列表  -->

    <!-- 工具条 -->
      <!-- 查询框 -->
      <div class="layui-collapse">
          <div class="layui-colla-item">
              <h2 class="layui-colla-title">查询条件</h2>
              <div class="layui-colla-content">
                  <form class="layui-form" method="post">
                      <div class="layui-inline">
                          <input type="text" name="serinput" placeholder="输入机械编码" autocomplete="off" class="layui-input" value="" style="width: 120%">
                      </div>

                      <div class="layui-inline" style="margin-left: 35px">
                          <input type="button" class="layui-btn layui-btn-small layui-btn-normal layui-icon" lay-submit lay-filter="formsubmit" value="&#xe615;查  询"/>
                      </div>
                  </form>
              </div>
          </div>
      </div>

      <div style="padding-top: 10px" >
        <a href="javascript:;" class="layui-btn layui-btn-normal" id="btnAdd">增加</a>
        <a href="javascript:;" class="layui-btn layui-btn-danger" id="btnClose">关闭</a>
      </div>

      <!-- 数据列表 -->

      <table class="layui-table" id="datasource" lay-filter="toolbar"></table>

{% include "common/jsfiles.html" %}

<script>
  var Typeinfo = {{ base|safe }};

  layui.config({
      base: '/static/layui/ext/',   // 模块所在目录
  }).extend({
      soulTable: 'soulTable'  // 模块别名
  });

  layui.use(['element', 'layer', 'table', 'soulTable'], function(){
      var $ = layui.jquery
          ,element = layui.element
          ,table = layui.table
          ,layer = layui.layer
          ,soulTable = layui.soulTable;

      $("#btnClose").click(function () {
          window.parent.layui.element.tabDelete('tabMain','Mencrepairplan');
      });

      //新增按钮事件
      $("#btnAdd").click(function () {
          parent.layer.open({
              type:   2,
              title:  '新增机械设备运维计划',
              area: ['1000px','370px'],
              fixed: false,
              content: "{% url 'mencrepairplan:add' %}",
              resize: false,
              move: false
          });
      });

      table.render({
          elem: '#datasource',
          height: 'full-120',
          url: "{% url 'mencrepairplan:get_datasource' %}",
          cols: [[
              {field:'FMecserialFID__FMecserialID', width: '20%', title: '机械唯一编码', sort: true, filter: true},
              {field:'FMecserialFID__FMectypeID', width: '15%', title: '机械类型', sort: true, templet: '<div>{% verbatim %}{{sotitle(d.FMecserialFID__FMectypeID, Typeinfo)}}{% endverbatim %}</div>', filter: true},
              {field:'FMecserialFID__FMecspec', width: '20%', title: '机械型号', sort: true, filter: true},
              {field:'FChecktype', width: '15%', title: '检查类型', sort: true, templet: '#tpType', filter: true},
              {field:'FInterval', width: '20%', title: '固定频率时间', sort: true, filter: true},
              {field:'FFirstcheckdate', width: '20%', title: '首次检查日期', sort: true, filter: true},
              {field:'FStatus', width: '15%', title: '状态', sort: true, templet: '#tpStatus'},
              {field:'', title: '操作', width: '20%', toolbar: '#tlbar', fixed: 'right'}
          ]],
          id: 'runreload'

          ,done: function () {
              soulTable.render(this)
          }
      });

      //监听查询条件提交
        form.on('submit(formsubmit)', function (data) {
            var serinput = $("input[name='serinput']").val();
            //alert(serinput);
            table.reload('runreload', {where: {resultdict:{FMecserialFID__FMecserialID: serinput}}});

            return false;
        });


      //监听工具栏按钮事件
      table.on('tool(toolbar)', function (obj) {
          var data = obj.data;           //获取当前行数据
          var layEvent = obj.event;      //获取当前行事件
          var tr = obj.tr;               //获取当前行tr的DOM数据
          var fid = {"fid":data.FID};

          switch (layEvent){
              case 'edit' :              //编辑按钮事件
                  parent.layer.open({
                      type:   2,
                      title:  '编辑机械设备运维计划',
                      area: ['1000px','370px'],
                      fixed: false,
                      content: "{% url 'mencrepairplan:edit' %}?fid="+data.FID,
                      resize: false,
                      move: false
                  });

                  break;

              case 'disabled' :               //禁用按钮事件
                  parent.layer.open({
                      content: '是否确定禁用该运维计划',
                      btn: ['确定','取消'],
                      yes: function (index) {
                          $.post("{% url 'mencrepairplan:disabled' %}?type=lock", fid, function (data) {
                              if (data.result=='0') {
                                  //window.parent.document.getElementById('Project').contentWindow.location.reload();
                                  table.reload('runreload', {where: {resultdict:{FMecspec: ''}}});
                              } else if (data.result=='2') {
                                  parent.layer.alert('运维计划禁用失败',{skin: 'layui-layer-lan', closeBtn: 0, anim: 0});
                              }

                          },"json");

                          parent.layer.close(index);
                      },
                      btn2: function (index) {
                      }
                  });

                  break;

              case 'enabled' :
                  parent.layer.open({
                      content: '是否确定启用该运维计划',
                      btn: ['确定','取消'],
                      yes: function (index) {
                          $.post("{% url 'mencrepairplan:disabled' %}?type=unlock", fid, function (data) {
                              if (data.result=='0') {
                                  //window.parent.document.getElementById('Organize').contentWindow.location.reload();
                                  table.reload('runreload', {where: {resultdict:{FMecspec: ''}}});
                              } else if (data.result=='2') {
                                  parent.layer.alert('运维计划启用失败',{skin: 'layui-layer-lan', closeBtn: 0, anim: 0});
                              }

                          },"json");

                          parent.layer.close(index);
                      },
                      btn2: function (index) {
                      }
                  });


                  break;

          }
      });
  });
</script>



<!--显示设备来源模板-->
<script type="text/html" id="tpType">
  {% verbatim %}
  {{#  if(d.FChecktype == 0){ }}
  <span>固定频率</span>
  {{#  } else if(d.FChecktype == 1) { }}
  <span>随机抽查</span>
  {{#  } }}
  {% endverbatim %}
</script>

  <!--显示启用状态模板-->
  <script type="text/html" id="tpStatus">
      {% verbatim %}
      {{#  if(d.FStatus == false){ }}
      <span style="color: red">禁用</span>
      {{#  } else if(d.FStatus == true) { }}
      <span style="color: green">启用</span>
      {{#  } }}
      {% endverbatim %}
  </script>

<!--生成操作工具栏-->
<script type="text/html" id="tlbar">
    {% verbatim %}
        <div class="layui-btn-group">
            <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit"><i class="iconfont icon-bianji"></i>编辑</a>

            {{# if(d.FStatus == true){ }}
            <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="disabled"><i class="iconfont icon-ccgl-yuliuyusuoding-6"></i>禁用</a>
            {{# } else if(d.FStatus == false){ }}
            <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="enabled"><i class="iconfont icon-ccgl-yuliuyusuoding-6"></i>启用</a>
            {{# } else { }}
            <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="disabled"><i class="iconfont icon-ccgl-yuliuyusuoding-6"></i>禁用</a>
            {{# } }}

        </div>
    {% endverbatim %}
</script>

</body>
</html>