ISMS/urls.py
from django.contrib import admin
from django.urls import path, include
from login import views
from common.views import generate_uuid, get_interface_param, generate_md5
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('login.urls'), name='login'),
    path('organize/', include('organize.urls'), name='organize'),
    path('project/', include('project.urls'), name='project'),
    path('genuuid/', generate_uuid, name='genuuid'),
    path('genmd5/', generate_md5, name='genmd5'),
    path('get_interface_param/<str:interID>/', get_interface_param),
    path('basedata/', include('basedata.urls'), name='basedata'),
    path('user/', include('user.urls'), name='user'),
    path('area/', include('area.urls'), name='area'),
    path('projectmap/', include('projectmap.urls'), name='projectmap'),
    path('team/', include('team.urls'), name='team'),
    path('group/', include('group.urls'), name='group'),
    path('personnel/', include('personnel.urls'), name='personnel'),
    path('personauth/', include('personauth.urls'), name='personauth'),
    path('device/', include('device.urls'), name='device'),
    path('devinterface/', include('devinterface.urls'), name='devinterface'),
    path('pedpassage/', include('pedpassage.urls'), name='pedpassage'),
    path('passagerecord/', include('passagerecord.urls'), name='passagerecord'),
    path('hatrule/', include('hatrule.urls'), name='hatrule'),
    path('hatalertlog/', include('hatalertlog.urls'), name='hatalertlog'),
    path('safetrain/', include('safetrain.urls'), name='safetrain'),
    path('envdatalog/', include('envdatalog.urls'), name='envdatalog'),
    path('envrule/', include('envrule.urls'), name='envrule'),
    path('envalarmlog/', include('envalarmlog.urls'), name='envalarmlog'),
    path('vehiclegate/', include('vehiclegate.urls'), name='vehiclegate'),
    path('vehiclefiles/', include('vehiclefiles.urls'), name='vehiclefiles'),
    path('vehiclepasslog/', include('vehiclepasslog.urls'), name='vehiclepasslog'),
    path('elecfencle/', include('elecfencle.urls'), name='elecfencle'),
    path('elecalarm/', include('elecalarm.urls'), name='elecalarm'),
    path('goodstype/', include('goodstype.urls'), name='goodstype'),
    path('unit/', include('unit.urls'), name='unit'),
    path('materials/', include('materials.urls'), name='materials'),
    path('receaccount/', include('receaccount.urls'), name='receaccount'),
    path('recepound/', include('recepound.urls'), name='recepound'),
    path('issueaccount/', include('issueaccount.urls'), name='issueaccount'),
    path('issuepound/', include('issuepound.urls'), name='issuepound'),
    path('abnpound/', include('abnpound.urls'), name='abnpound'),
    path('menchanical/', include('menchanical.urls'), name='menchanical'),
    path('menccheck/', include('menccheck.urls'), name='menccheck'),
    path('mencrepairplan/', include('mencrepairplan.urls'), name='mencrepairplan'),
    path('mencrepairlog/', include('mencrepairlog.urls'), name='mencrepairlog'),
    path('monitordev/', include('monitordev.urls'), name='monitordev'),
    path('dsps/', include('dsps.urls'), name='dsps'),
    path('envdetection/', include('envdetection.urls'), name='envdetection'),
    path('personinfomap/', include('personinfomap.urls'), name='personinfomap'),
    path('mainanalyse/', include('mainanalyse.urls'), name='mainanalyse'),
    path('elevator/', include('elevator.urls'), name='elevator'),
    path('towercrane/', include('towercrane.urls'), name='towercrane'),
    path('mapview/', include('mapview.urls'), name='mapview'),
    path('visitor/', include('visitor.urls'), name='visitor'),
    path('usergroup/', include('usergroup.urls'), name='usergroup'),
    path('interface/', include('interface.urls'), name='interface'),
    path('unloading/', include('unloading.urls'), name='unloading'),
    path('busmenu/', include('busmenu.urls'), name='busmenu'),
    path('appkey/', include('appkey.urls'), name='appkey'),
    path('ismsapi/', include('ismsapi.urls'), name='ismsapi'),
    path('devinterfacesrv/', include('devinterfacesrv.urls'), name='devinterfacesrv'),
    path('datacockpit/', include('datacockpit.urls'), name='datacockpit'),
    path('devicecockpit/', include('devicecockpit.urls'), name='devicecockpit'),
    path('videocockpit/', include('videocockpit.urls'), name='videocockpit'),
    path('prjprocess/', include('prjprocess.urls'), name='prjprocess'),
    path('epidcockpit/', include('epidcockpit.urls'), name='epidcockpit'),
    path('prjreport/', include('prjreport.urls'), name='prjreport')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

issuepound/urls.py
from django.urls import path
from . import views

app_name="issuepound"

urlpatterns = [
    path('entrance/', views.entrance.as_view(), name='entrance'),
    path('get_datasource/', views.get_datasource.as_view(), name='get_datasource'),
    path('add/', views.add.as_view(), name='add'),
    path('edit/', views.edit.as_view(), name='edit'),
    path('insert/', views.insert.as_view(), name='insert'),
    path('get_originbill_datasource/', views.get_originbill_datasource.as_view(), name='get_originbill_datasource'),
    path('get_material_datasource/', views.get_material_datasource.as_view(), name='get_material_datasource'),
    path('recevoid/', views.recevoid.as_view(), name='recevoid'),
    path('get_unitid/', views.get_unitid.as_view(), name='get_unitid'),
    path('show_originupload/', views.show_originupload.as_view(), name='show_originupload')
]

issuepound/forms.py
from django.forms import ModelForm
from django import forms
from django.forms import widgets as Fwidgets
from receaccount.models import *

class IssuePoundModelForm(ModelForm):

    CREATED_PRJ = forms.ChoiceField(widget=forms.Select(attrs={'lay-verify': 'required'}), required=False)
    FOperationalOrgID = forms.ChoiceField(widget=forms.Select(attrs={'lay-verify': 'required'}), required=False)
    FWorktypeID = forms.ChoiceField(widget=forms.Select(attrs={'lay-verify': 'required'}), required=False)
    FWaybillPicpath = forms.ImageField(required=False, widget=forms.FileInput(attrs={'class': 'layui-input', 'style': 'display: none'}))

    class Meta:
        model = materialsaccount
        fields = '__all__'

        widgets = {
            'FID': Fwidgets.Input(attrs={'type': 'hidden'}),
            'FPoundNo': Fwidgets.Input(attrs={'class': 'layui-input', 'lay-verify': 'required', 'autocomplete': 'off'}),
            'FStatus': Fwidgets.Select(attrs={'lay-verify': 'required', 'disabled': 'disabled'}),
            'F1stWeighTime': Fwidgets.Input(attrs={'class': 'layui-input', 'lay-verify': 'required', 'autocomplete': 'off'}),
            'F2ndWeighTime': Fwidgets.Input(attrs={'class': 'layui-input', 'lay-verify': 'required', 'autocomplete': 'off'}),
            'F1stWeigh': Fwidgets.Input(attrs={'class': 'layui-input', 'lay-verify': 'required', 'autocomplete': 'off'}),
            'F2ndWeigh': Fwidgets.Input(attrs={'class': 'layui-input', 'lay-verify': 'required', 'autocomplete': 'off'}),
            'FWaybillNo': Fwidgets.Input(attrs={'class': 'layui-input', 'lay-verify': 'required', 'autocomplete': 'off'}),
            'FWaybillDate': Fwidgets.Input(attrs={'class': 'layui-input', 'lay-verify': 'required', 'autocomplete': 'off'}),
            'FWeighPerson': Fwidgets.Input(attrs={'class': 'layui-input', 'lay-verify': 'required', 'autocomplete': 'off', 'readonly': 'true'}),
            'FPlate': Fwidgets.Input(attrs={'class': 'layui-input', 'lay-verify': 'required', 'autocomplete': 'off'}),
            'FWarehouseID': Fwidgets.Input(attrs={'class': 'layui-input', 'autocomplete': 'off'}),
            'FUsesite': Fwidgets.Input(attrs={'class': 'layui-input', 'autocomplete': 'off'}),
            'FDesc': Fwidgets.Textarea(attrs={'class': 'layui-textarea', 'autocomplete': 'off', 'rows': '1'}),

        }

class IssuePoundMaterModelForm(ModelForm):

    FMaterID = forms.ChoiceField(widget=forms.Select(attrs={'lay-verify': 'required', 'lay-filter': 'selMater'}), required=False)
    FUnitID = forms.ChoiceField(widget=forms.Select(attrs={'lay-verify': 'required'}), required=False)

    class Meta:
        model = materaccountgoods
        fields = '__all__'

        widgets = {
            'FID': Fwidgets.Input(attrs={'type': 'hidden'}),
            'FPID': Fwidgets.Input(attrs={'type': 'hidden'}),
            'FWaybillQty': Fwidgets.Input(attrs={'class': 'layui-input', 'lay-verify': 'required', 'autocomplete': 'off'}),
            'FConfirmQty': Fwidgets.Input(attrs={'class': 'layui-input', 'lay-verify': 'required', 'autocomplete': 'off'}),
            'FDeviationQty': Fwidgets.Input(attrs={'class': 'layui-input', 'lay-verify': 'required', 'autocomplete': 'off', 'readonly': 'true'}),

        }

issuepound/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse
from django.http import HttpRequest
from django.shortcuts import redirect
from django.db.models import Q
from receaccount.models import materialsaccount as T_MaterialAccount
from receaccount.models import materaccountgoods as T_MaterialAccountGoods
from organize.models import organize
from materials.models import materials
from project.models import project
from basedata.models import base
from goodstype.models import goodstype
from unit.models import unit as T_Unit
from common.views import *
from django.http import JsonResponse
from .forms import *
import json
from django.utils import timezone
from django.forms import widgets as Fwidge
from django.core.exceptions import ObjectDoesNotExist
from baseframe.baseframe import *
# Create your views here.

#控制器入口
class entrance(EntranceView_base):
    def set_view(self, request):
        prj_id = self.request.session['PrjID']

        self.template_name = 'content/issuepound/issuepoundinfo.html'
        self.query_sets = [
            organize.objects.filter(Q(FStatus=True)),
            base.objects.filter(Q(FPID='58a9645abca111e997d77831c1d24216')),
            materials.objects.filter(Q(CREATED_PRJ=prj_id)),
            goodstype.objects.filter(Q(CREATED_PRJ=prj_id))
        ]
        self.quer_set_fieldnames = ['FOrgname', 'FBase', 'FName', 'FGoodsType']

#返回table数据及查询结果
class get_datasource(get_datasource_base):
    def get_queryset(self, reqeust):
        prj_id = self.request.session['PrjID']
        serinput = self.request.GET.get("resultdict[FPID__FPoundNo]", '')
        self.type = 1

        issuepound_info = T_MaterialAccountGoods.objects.filter(Q(FPID__CREATED_PRJ=prj_id), Q(FPID__FPoundNo__contains=serinput), Q(FPID__FReceivetype=1), ~Q(FPID__FStatus=2)).values('FPID__FID', 'FPID__FPoundNo', 'FPID__FPlate', 'FPID__FOperationalOrgID','FPID__FWorktypeID', 'FMaterID__FName', 'FPID__CREATED_TIME','FWaybillQty', 'FConfirmQty', 'FDeviationQty', 'FPID__FStatus')

        return issuepound_info


#链接新增模板
class add(add_base):
    def set_view(self, request):
        prj_id = self.request.session['PrjID']

        self.template_name = 'content/issuepound/issuepoundadd.html'
        self.objForm = IssuePoundModelForm
        self.query_sets = [
            organize.objects.filter(Q(FStatus=True)),
            base.objects.filter(Q(FPID='58a9645abca111e997d77831c1d24216')),
            project.objects.filter(Q(FStatus=True))
        ]
        self.query_set_idfields = ['FOperationalOrgID', 'FWorktypeID', 'CREATED_PRJ']
        self.query_set_valuefields = ['FOrgname', 'FBase', 'FPrjname']

        prefix = 'F' + timezone.now().strftime("%Y%m%d")
        pound_no = gensequence('issuepound', prefix, 4, 1)
        self.context['poundNo'] = pound_no

        objMaterForm = IssuePoundMaterModelForm()
        materials_info = materials.objects.filter(Q(CREATED_PRJ=prj_id))
        unit_info = T_Unit.objects.filter(Q(FStatus=True))

        objMaterForm.fields['FMaterID'].choices = get_dict_object(request, materials_info, 'FID', 'FName')
        objMaterForm.fields['FUnitID'].choices = get_dict_object(request, unit_info, 'FID', 'FUnit')

        self.context['objMaterForm'] = objMaterForm
        self.context['goodstype'] = 'null'
        self.context['unit'] = 'null'


#链接编辑模板
class edit(edit_base):
    def set_view(self, request):
        self.template_name = 'content/issuepound/issuepoundadd.html'
        self.model = T_MaterialAccount
        self.objForm = IssuePoundModelForm
        self.query_sets = [
            organize.objects.filter(Q(FStatus=True)),
            base.objects.filter(Q(FPID='58a9645abca111e997d77831c1d24216')),
            project.objects.filter(Q(FStatus=True))
        ]
        self.query_set_idfields = ['FOperationalOrgID', 'FWorktypeID', 'CREATED_PRJ']
        self.query_set_valuefields = ['FOrgname', 'FBase', 'FPrjname']

        goodstype_info = get_dict_table(goodstype.objects.filter(Q(FPID__isnull=False)), 'FID', 'FGoodsType')
        unit_info = get_dict_table(T_Unit.objects.filter(Q(FStatus=True)), 'FID', 'FUnit')
        self.context['goodstype'] = goodstype_info
        self.context['unit'] = unit_info

        id = ''.join(str(self.request.GET.get('fid')).split('-'))
        issuepound = T_MaterialAccount.objects.get(Q(FID=id))
        self.context['inpic1'] = str(issuepound.FInPicpath1)
        self.context['outpic1'] = str(issuepound.FOutPicpath1)


#处理新增及保存数据
class insert(insert_base):
    def set_view(self, request):
        self.model = T_MaterialAccount
        self.objForm = IssuePoundModelForm
        self.query_sets = [
            organize.objects.filter(Q(FStatus=True)),
            base.objects.filter(Q(FPID='58a9645abca111e997d77831c1d24216')),
            project.objects.filter(Q(FStatus=True)),
        ]
        self.query_set_idfields = ['FOperationalOrgID', 'FWorktypeID', 'CREATED_PRJ']
        self.query_set_valuefields = ['FOrgname', 'FBase', 'FPrjname']

        self.set_fields = ['FReceivetype']
        self.set_value = [1]

    def set_view_aftersave(self, request):
        if self.request.GET.get('actype') == 'insert':
            fpid = self.request.POST.get('FID')
            isusepound_info = T_MaterialAccount.objects.get(FID=fpid)

            issuepoundgoods_info =  T_MaterialAccountGoods.objects.create(FPID=isusepound_info)
            #recepoundgoods_info.FPID = recpound_info.FID
            issuepoundgoods_info.FMaterID_id = self.request.POST.get('FMaterID')
            issuepoundgoods_info.FUnitID = self.request.POST.get('FUnitID')
            issuepoundgoods_info.FWaybillQty = self.request.POST.get('FWaybillQty')
            issuepoundgoods_info.FConfirmQty = self.request.POST.get('FConfirmQty')
            issuepoundgoods_info.FDeviationQty = self.request.POST.get('FDeviationQty')
            issuepoundgoods_info.CREATED_PRJ = self.request.session['PrjID']
            issuepoundgoods_info.CREATED_ORG = self.request.session['UserOrg']
            issuepoundgoods_info.CREATED_BY = self.request.session['UserID']
            issuepoundgoods_info.UPDATED_BY = self.request.session['UserID']
            issuepoundgoods_info.CREATED_TIME = timezone.now()
            issuepoundgoods_info.save()


#返回原始运单信息table
class get_originbill_datasource(get_datasource_base):
    def get_queryset(self, reqeust):
        fid = ''.join(str(self.request.GET.get('fid')).split('-'))

        originbill_info = T_MaterialAccount.objects.filter(Q(FID=fid))
        return  originbill_info


#返回材料明细信息table
class get_material_datasource(get_datasource_base):
    def get_queryset(self, reqeust):
        fid = ''.join(str(self.request.GET.get('fid')).split('-'))

        self.type = 1
        material_info = T_MaterialAccountGoods.objects.filter(Q(FPID=fid)).values('FMaterID__FMaterID', 'FMaterID__FName', 'FMaterID__FGoodsTypeID', 'FMaterID__FSpec', 'FMaterID__FUnitID', 'FMaterID__FTexture', 'FWaybillQty', 'FConfirmQty', 'FDeviationQty')
        return material_info


#处理作废
class recevoid(disabled_base):
    def set_view(self, request):
        self.model = T_MaterialAccount
        self.type = 1
        self.status = [1, 2]


#根据物料自动获取计量单位
class get_unitid(View):
    def post(self, request):
        response_data = {}

        fid = request.POST.get('fid')

        try:
            mater_info = materials.objects.get(Q(FID=fid))
            response_data['result'] = '0'
            response_data['unitid'] = mater_info.FUnitID

            return HttpResponse(json.dumps(response_data))

        except ObjectDoesNotExist:
            response_data['result'] = '1'
            return HttpResponse(json.dumps(response_data))


#上传原始运单附件
class show_originupload(View):
    def post(self, request):
        fid = request.POST.get('FPID')
        issuepound_info = T_MaterialAccount.objects.get(Q(FID=fid))

        issuepound_info.FWaybillNo = request.POST.get('FWaybillNo')
        issuepound_info.FWaybillDate = request.POST.get('FWaybillDate')
        issuepound_info.FWaybillPicpath = request.FILES.get('FWaybillPicpath')
        issuepound_info.save()

        url = '/issuepound/show_originupload?fid='+request.POST.get('FPID')
        return redirect(url)

    def get(self, request):
        fid = ''.join(str(request.GET.get('fid')).split('-'))
        obj = IssuePoundModelForm()

        return render(request, "content/issuepound/originupload.html", {'obj': obj, 'fid': fid})

templates/content/issuepound/issuepoundinfo.html
<!DOCTYPE html>
<html>
<head>
    {% include "common/resfiles.html" %}
</head>
<body style="overflow: hidden;">

  <!--安全帽规则信息列表  -->

    <!-- 工具条 -->
      <!-- 查询框 -->
      <div class="layui-collapse">
          <div class="layui-colla-item">
              <h2 class="layui-colla-title">查询条件</h2>
              <div class="layui-colla-content">
                  <form class="layui-form" method="post">
                      <div class="layui-inline">
                          <input type="text" name="serinput" placeholder="输入磅单号码" autocomplete="off" class="layui-input" value="" style="width: 120%">
                      </div>

                      <div class="layui-inline" style="margin-left: 35px">
                          <input type="button" class="layui-btn layui-btn-small layui-btn-normal layui-icon" lay-submit lay-filter="formsubmit" value="&#xe615;查  询"/>
                      </div>
                  </form>
              </div>
          </div>
      </div>

      <div style="padding-top: 10px" >
          <a href="javascript:;" class="layui-btn layui-btn-normal" id="btnAdd">补录</a>
          <a href="javascript:;" class="layui-btn layui-btn-danger" id="btnClose">关闭</a>
      </div>

      <!-- 数据列表 -->

      <table class="layui-table" id="datasource" lay-filter="toolbar"></table>

{% include "common/jsfiles.html" %}

<script>
  var Orginfo = {{ organize|safe }}
  var Worktypeinfo = {{ base|safe }};
  var Materinfo = {{ materials|safe }};
  var Goodstypeinfo = {{ goodstype|safe }};

  layui.config({
        base: '/static/layui/ext/',   // 模块所在目录
  }).extend({
        soulTable: 'soulTable'  // 模块别名
  });


  layui.use(['element', 'layer', 'table', 'soulTable'], function(){
      var $ = layui.jquery
          ,element = layui.element
          ,table = layui.table
          ,layer = layui.layer
          ,soulTable = layui.soulTable;

      $("#btnClose").click(function () {
          window.parent.layui.element.tabDelete('tabMain','Issuepound');
      });

      //新增按钮事件
      $("#btnAdd").click(function () {
          parent.layer.open({
              type:   2,
              title:  '补录发料磅单',
              area: ['1280px','640px'],
              fixed: false,
              content: "{% url 'issuepound:add' %}",
              resize: false,
              move: false
          });
      });

      table.render({
          elem: '#datasource',
          height: 'full-120',
          url: "{% url 'issuepound:get_datasource' %}",
          cols: [[
                {title: '#', width: '5%', collapse: true, children:[
                    {
                        title: '磅单物料明细'
                        ,url: function (row) {
                            return "{% url 'issuepound:get_material_datasource' %}?fid="+row.FPID__FID
                        }
                        ,height: 100
                        ,page: false
                        ,cols: [[
                            {field: 'FMaterID__FMaterID', title: '物料编码', width: '15%', sort: true, filter: true},
                            {field: 'FMaterID__FName', title: '物料名称', width: '20%', sort: true, filter: true},
                            {field: 'FMaterID__FGoodsTypeID', title: '物料类别', width: '20%', sort: true, filter: true, templet: '<div>{% verbatim %}{{sotitle(d.FMaterID__FGoodsTypeID, Goodstypeinfo)}}{% endverbatim %}</div>'},
                            {field: 'FWaybillQty', title: '运单数量', width: '20%', sort: true, filter: true},
                            {field: 'FConfirmQty', title: '确认数量', width: '20%', sort: true, filter: true},
                            {field: 'FDeviationQty', title: '偏差', width: '20%', sort: true, filter: true},
                        ]]
                        ,done: function () {
                            soulTable.render(this);
                        }
                    }
                ]},

              {field:'FPID__FPoundNo', width: '20%', title: '磅单编号', sort: true, filter: true},
              {field:'FPID__FPlate', width: '20%', title: '车牌号码', sort: true, filter: true},
              {field:'FPID__FOperationalOrgID', width: '20%', title: '供应单位', sort: true, templet: '<div>{% verbatim %}{{sotitle(d.FPID__FOperationalOrgID, Orginfo)}}{% endverbatim %}</div>', filter: true, excel: {cellType: 's'}},
              {field:'FPID__FWorktypeID', width: '15%', title: '收料类型', sort: true, templet: '<div>{% verbatim %}{{sotitle(d.FPID__FWorktypeID, Worktypeinfo)}}{% endverbatim %}</div>'},
              {field:'FPID__FStatus', width: '15%', title: '单据状态', sort: true, templet: '#tpStatus'},
              {field:'', title: '操作', width: '20%', toolbar: '#tlbar', fixed: 'right'}
          ]],
          id: 'runreload'

          ,filter: {
              items: ['column', 'data', 'condition', 'editCondition', 'excel', 'clearCache'] //表格右键菜单
              , cache: true
          }

          ,done: function () {
            soulTable.render(this)
          }
      });


      //监听查询条件提交
        form.on('submit(formsubmit)', function (data) {
            var serinput = $("input[name='serinput']").val();
            //alert(serinput);
            table.reload('runreload', {where: {resultdict:{FPID__FPoundNo: serinput}}});

            return false;
        });


      //监听工具栏按钮事件
      table.on('tool(toolbar)', function (obj) {
          var data = obj.data;           //获取当前行数据
          var layEvent = obj.event;      //获取当前行事件
          var tr = obj.tr;               //获取当前行tr的DOM数据
          var fid = {"fid":data.FPID__FID};

          switch (layEvent){
              case 'edit' :              //编辑按钮事件
                  parent.layer.open({
                      type:   2,
                      title:  '编辑发料磅单',
                      area: ['1280px','640px'],
                      fixed: false,
                      content: "{% url 'issuepound:edit' %}?fid="+data.FPID__FID,
                      resize: false,
                      move: false
                  });

                  break;

              case 'invalid':           //作废按钮事件
                  parent.layer.open({
                      content: '是否确定验收该发料磅单',
                      btn: ['确定','取消'],
                      yes: function (index) {
                          $.post("{% url 'issuepound:recevoid' %}?type=unlock", fid, function (data) {
                              if (data.result=='0') {
                                  //window.parent.document.getElementById('Project').contentWindow.location.reload();
                                  table.reload('runreload', {where: {resultdict:{FPID__FPoundNo: ''}}});
                              } else if (data.result=='2') {
                                  parent.layer.alert('单据验收失败',{skin: 'layui-layer-lan', closeBtn: 0, anim: 0});
                              }

                          },"json");

                          parent.layer.close(index);
                      },
                      btn2: function (index) {
                      }
                  });

                  break;
          }
      });
  });


</script>


  <!--显示状态模板-->
  <script type="text/html" id="tpStatus">
      {% verbatim %}
      {{#  if(d.FPID__FStatus == 0){ }}
      <span>称重</span>
      {{#  } else if(d.FPID__FStatus == 1) { }}
      <span style="color: purple">补录</span>
      {{#  } else if(d.FPID__FStatus == 2) { }}
      <span style="color: green">验收</span>
      {{#  } else if(d.FPID__FStatus == 3) { }}
      <span style="color: red">作废</span>
      {{#  } }}
      {% endverbatim %}
  </script>


<!--生成操作工具栏-->
<script type="text/html" id="tlbar">
    {% verbatim %}
        <div class="layui-btn-group">
            <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit"><i class="iconfont icon-bianji"></i>编辑</a>
            <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="invalid"><i class="layui-icon">&#xe640;</i>验收</a>

        </div>
    {% endverbatim %}
</script>


</body>
</html>